language: python
python:
- '3.6'
install:
- pip install ansible>=2.4 molecule>=2.6 testinfra>=1.10 apache-libcloud requests
  google-auth pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: V8qXnz0eQLsorKL8+kNuI5W3Q1ji3s2eQ7LtwxTAZRbzwYg4zeEPx0xNeD61BIdDszyyWV+aY4lnctD3VB8p5/uCulmZZ8G5ptCIuH9mtL/IUKZaBfP3G1P2pp/OEuZXGgDdwriewpjH0+WAygOlfmsJ1dMffj9LsZQNXSIDsyVgBWomb/RdZF+fkfS8eZYteNig7NMWIskf0qLdusGiIXY5uyTKTHmE4WxOp4vivYmxkv7lGs6LzToTdlxjWiV7uHMxgQVvg4rKma2SWQjNSAEdablcPpx2E2UDKvr0m5z04YQP+8qFaipaeMVYfbMSEGCdewio3ZVhy52aJspVL9u0duggq4b+iNO0lZ77BZ7Qy6kasEmpaySDJnLPuU7AFhxxkFb5ZU37J6yCaYfgM5bt1IB1bRZftEBrsUrH7iCw1bP13AgInCnTbnyoj+z5Nld5MEEhHyVRZq4yZKYb6jtduT3QWQLK29I2ewTfEhmsl5XQRhk3FCZUI+eIMN+50ZgqG0rQZxNQJmAW2LPmIFAoLp47P71DDPO1NjZBjwKtv3gmTH7OEvOAn4SuYt9VpWaJKEslaeVPX1AgwFcLcUOXY8czeHN7Edtd/Dgw34Am+39aW++pOqTbP7Rk96INb/bObE1wQEdH7SqbCo6p3PU3VaR2OTnyVO10qBCCPxU=
  - secure: vJSDxoLAQU3V8/h5Sxw+KEwzyfzB0k7frabLL3S8IKngOaN5zrC5D9iUWB5m9kxVCryc002EEyqvUMmHMf4CWKYvxZW3S205dzmQ5QOEpgJ0ggNwr0BON8M2/DcKDx1A97K86gVZV8wWIfzZkhxob9N9baWxcnHH2XtSl/UlaDMY2nJbs8VGQ6DUvlRmoROsXwFPnrhfKweomarGMpsoVU+ZIWSBbCMo4yKLL2H18eWl9evMZl/KSwwcV5EFzj0oi+6NVmueYKmvT3Vi+nJjjJfGPY4dnaVdROAiNlbO9IRBgHZ9OJEDcefV3W61JutYEXbqddWTYMcw4XxxOHv+oJ8PiKESiGIHYxrGfles7Cu45hOE6dznc2690T0K0LV+jss5Enu3C87qwFzpIYsk6Hpo0Q6nWlEl9zmUy7xso41hjyW9sia3UPXHD/w94aXLeBXq9KJB7/oXVd9t2o2H7ANcA+J2pZH6YT6LZhyLoKWuAzcIc0UVhXaZ0K7h7PcdcUYcXUs3gM+GXQDjNL4dKNT0Z3xT9xQ1TBnYkjszGCxQp3dzn4jOK841hxYMnzQq2frN1xHVr/by5T89FN6b0g/PIFKwqULs75iXNcz41ZkmmBXsXdBzqf5ezxN1pHsQaitYYoWnDgqjgkhpV1Ra2RUdE7ZJUVdQ9i8N2syh2gg=
  - secure: plRkILXzWsIHEu5G/lC0FGtbO0WZCh6CdBkSh4K4YT1iLaR9wKn5wpkR/5WVSxGP1HjEt4l2sLYuR/OsWsKeM0JhTbIQy4Qn8pyTzon9weteJ24f/dU/Uor7lQslley8cDlNNyYfkRwNeCq/WZa2UHCLlZcX7+aSjVItFPOkiRNSAB/Bn7rdxYwHWfoqjj53zfbGMHifqQ6K0Vc442ek4TPuuCvRHaLvcGPQGBFQIjyDk6iHbTa5927QUCl3UmYPMXzD8Ez/lnuxXbDkWZKgK7Ix8sZJLHzq7EL+FEwjvF4qwthiwUACpPZsYQ4dZAJfT/beZQF2IqLdw7XJMc6XgWV4WA7J7WDDp7AdhlVnLNVd849wJ9N3fK+5Fl/wOKSUQJWFh3+dQzYZHpQLYevG3kV4zq9/lpHVsotaJ3VQjdQVSJwymaO5QCigS5ojoU1CgBnmemgJNwVeRps/+cfsV3pdwYnzNhGzj+gSgmNvjYa6TqnF+TowEW0a5skH45k3m4Pu39N6Qu/1e4PJZlVBXlkX6PEmzNKFhAHYsDeDDebHHyNUNRrODgBhRbI/WrJn3h7vd+rrn9tCiR5XSswiVtom6UsnRoz/F6AVMlRwLfI+N3UOenMCQpFy/18Jz3JvPf0sX9wV4ml41vBaxCBVzVK2MilON/AqCtxR89LwCRk=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_2db64f925e5c_key -iv $encrypted_2db64f925e5c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    rooms:
      secure: mULCIY9pek12M+9Nx/FowUG1VcXeTgXsvlu+35pzHfASrzgjcxadT5H0ARNUjVZiogxe1D2e4bfp7Jgr3qwh1vy761l+34L/Pe+jj6A5MVFCOT5NpuYQ651mPhBgRWYnQrOmxv4PmdOlmyZH4XXYwHl5YbUbb4ZONsAPscV3QiBcel4fPMzfrUdrL8AsRRD3esF5lKxBO+o6OPwle9A8M6I76cYXtlbbam9coJeZVSSculnQHj1VsMGcuQXstc/ULM0bXw0IjrQlESB9T0iD3/L57UxPWjcCAEGfz1wF8kjPuNBQpSj0t318EyXPrIROzz/CxEXhI8H+LcxAbkkV0YQUHEeQvp1CvigiuzvlxoZ1rZe9LFwNQcj/Ism7OCbwX9WO1KWEXgH4o9cy3CdA/5q8etvFR1jB0D/aWtDYzXaM2Y0jACvpfphR6v75+ALpbjlhV8yDpDxgLS3LxR4DffsDQHElQwj36o5ZxbooYpv7IGnhQOw91LDdSfHgx9C+QZfukXDqBw3MPey8bk+R1Dnlqg/6WCSf3hrRme1RAOseOVvfe+xz2QEHDd6L2hdgD7884VVQtb/qkTl9WY+VCK888Tu9VBPaeaaghqv2fcMfLwPGQt6R9TktWaJ03kSBch+ScN+tRGlmnapNi6YUVUBIH2l32IhGhkqtLqK8DbQ=
